### ISSUE TITLE
Name and label encoding in export

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#10]
The web tool exports human readable unicode values for names and labels. But Exportify the python 2.x tool encodes them as machine readable escaped unicode values. 

- If running our JSON thru exportify tool generates the machine readible version then a-okay can close this.
- If not then we need to decide:
    - human readable is okay
    - or do extra logic in our tool to translate to the machine format.

**Comment by iandees** [comment]
Now that we're running through exportify this should be completed.
