### ISSUE TITLE
Use pretty language display in name and label field elements

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#11]
Right now we just say "eng" instead of "English" in the little badges. While we need to store "eng" in the WOF JSON record, "English" is far easier for humans to read, especially for other languages.

- [x] Pretty display of language names
    - [x] names
    - [x] labels
- [ ]  Also allow auto complete for full language names, not just 3-char codes.
    - [ ] names
    - [ ] labels

**Comment by iandees** [comment]
The most popular languages are now expanded on both localized names and labels. To add more, we modify this code here:

https://github.com/iandees/wof-editor/blob/5d2ec63829e23c8a642219bd9baf7dadb56e6044/editor/place/views.py#L41-L81

**Comment by iandees** [comment]
Autocomplete for the expanded name in the "filter" boxes will be a little bit trickier and I'll leave that for now.

**Comment by nvkelso** [comment]
Let's close this one, and continue autocomplete in https://github.com/iandees/wof-editor/issues/20 later.
