### ISSUE TITLE
Add concordances to forms

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#13]
Add `wof:concordances` (but ignore wof:concordanes_alt for now). 

EG: 

> wof:concordances":{ "gp:id":22659979, "qs_pg:id":531894},

@stepps00 can you provide list list of common concordances prefixes, please?

**Comment by stepps00** [comment]
Here are some of the more common concordance properties and the name of the concordance:

```
{
	"gn:id": "GeoNames",
	"wk:page": "Wikipedia",
	"wd:id": "Wikidata",
	"gp:id": "GeoPlanet",
	"qs_pg:id": "Quattroshapes Point Gazetteer",
	"loc:id": "Library of Congress",
	"fips:code": "Federal Information Processing Standards (FIPS)",
	"hasc:id": "Statoids HASC",
	"qs:id": "Quattroshapes",
	"woe:id": "Where On Earth",
	"iso:id": "International Organization for Standardization"
}
```

**Comment by iandees** [comment]
One thing to note on this is that I don't see a way to determine if a value should be an integer or a string, so I'll likely end up converting some things to strings.

**Comment by nvkelso** [comment]
Agree they should default to strings... because even FIPS codes look like ints but are actually strings (leading 0).

**Comment by iandees** [comment]
I added initial support for concordances:

![image](https://user-images.githubusercontent.com/261584/74072176-9712c580-49cb-11ea-8be2-c9e03c98bb64.png)

I didn't do the filtering thing that I do for alt names and labels yet, so it currently doesn't support adding new concordances and it's showing all the concordances at once on the page. This is a little unwieldy maybe.

**Comment by nvkelso** [comment]
I dig it. There aren't every very many of them (while names run on and on), so I'm  fine with just listing them.

Can we add ability to add a new concordance to list and call it done?

**Comment by nvkelso** [comment]
Can we add one-off logic for the following concordance values to force them to be ints to prevent diff noise... the others can be assumed string:

```
        "gn:id": {
            "type": "integer"
        },
        "gp:id": {
            "type": "integer"
        },
        "qs:id": {
            "type": "integer"
        },
        "qs_pg:id": {
            "type": "integer"
        },
```

See also:

- https://github.com/whosonfirst-data/whosonfirst-data-admin-xy/pull/12/files
- https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof/concordances.json

**Comment by iandees** [comment]
You can add new concordances and they are transformed into ints if on that list.

**Comment by nvkelso** [comment]
Working for me:

![image](https://user-images.githubusercontent.com/853051/74187940-636db080-4c02-11ea-83db-fb25a77e3db6.png)
