### ISSUE TITLE
Add placetype_alt to form

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#14]
We should see what the existing placetype is (but read only because of lifecycle rules), and we should also add an editable `placetype_alt` string field. It's rare, but important for country capitals especially.

**Comment by iandees** [comment]
`wof:placetype` is visible as an uneditable text field and `wof:placetype_alt` is editable as a list:

![image](https://user-images.githubusercontent.com/261584/74070097-a68f1000-49c5-11ea-8ca5-d5679a0aede1.png)

**Comment by nvkelso** [comment]
Verified!
