### ISSUE TITLE
Github auth should be tied to WOF not a person

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#21]
"authorize IanDees" should probably say "authorize WOF Editor" on login?

**Comment by iandees** [comment]
It'd help to have a screenshot. If it's the text I'm thinking of, that's the owner of the OAuth app. We can change it by transferring ownership of the OAuth app to the Who's on First GitHub organization. I believe I have to be an admin of that GitHub org to be able to transfer ownership.

**Comment by nvkelso** [comment]
Sounds like we need to move the OAuth app into WOF Github org.

![image](https://user-images.githubusercontent.com/853051/73963134-96433c00-48c4-11ea-8f43-953c745ca479.png)

**Comment by nvkelso** [comment]
Nextzen is good for now... some day we'll move to WOF org.

![image](https://user-images.githubusercontent.com/853051/73963273-d1456f80-48c4-11ea-8411-5e4ad28d13b3.png)
