### ISSUE TITLE
Formatting: add space between logged in username and logout text

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#22]
![image](https://user-images.githubusercontent.com/853051/73893526-c3450f80-482e-11ea-8e13-44163577a872.png)

**Comment by nvkelso** [comment]
Perhaps move username and Logout all the way over to the right, too?

**Comment by iandees** [comment]
This is a casualty of switching to Bootstrap 4 for the validation stuff. Should be fixed now.

**Comment by nvkelso** [comment]
Verified!
