### ISSUE TITLE
Add autocomplete for language codes to spoken and official language fields

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#23]
Copy the autocomplete on localized names and labels to the two spoken and official language fields, too.

![image](https://user-images.githubusercontent.com/853051/73893602-fa1b2580-482e-11ea-9a88-b33564153a20.png)

**Comment by iandees** [comment]
I added languages to the Tagify whitelist for the language inputs:

![image](https://user-images.githubusercontent.com/261584/74194789-97a39a00-4c1f-11ea-89ff-22cf621df47d.png)

The name expansions continue to be hard to figure out, so I'm going to leave it as-is for now.

**Comment by thisisaaronland** [comment]
See also:

* https://www.w3.org/International/articles/language-tags/
* https://r12a.github.io/app-subtags/

**Comment by nvkelso** [comment]
WFM
