### ISSUE TITLE
On validation error on PR or export, scroll page to top

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#24]
I kept pressing the PR and export buttons at the bottom of the page wondering why they didn't do anything...

Then, because I had deliberately put in bad values, I scrolled up and noticed some fields had ! next to them saying fix a problem. 

Then I scrolled all the way up and saw there were these helpful red alerts. Probably only one general alert is needed, not duplicates.

If there are errors on pressing either PR or Export buttons, we should scroll the page all the way up to show the alerts.

![image](https://user-images.githubusercontent.com/853051/73893724-4e260a00-482f-11ea-8229-568efe31bf95.png)

**Comment by iandees** [comment]
I added scrolling to the top 👍

**Comment by nvkelso** [comment]
Working for me.
