### ISSUE TITLE
On PR of modified NYC record I get bad server error

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#25]
![image](https://user-images.githubusercontent.com/853051/73893886-c096ea00-482f-11ea-8062-ba9813d4ae48.png)

**Comment by nvkelso** [comment]
eg: https://93ctehyu4h.execute-api.us-east-1.amazonaws.com/dev/place/85977539/edit

**Comment by nvkelso** [comment]
On retry it worked fine multiple times. Resourcing issue?

**Comment by iandees** [comment]
Yea, this is likely a timeout issue. I saw a couple requests that were taking exactly 15 seconds, which is the timeout.
