### ISSUE TITLE
Error on escaping localized name variants

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#26]
I don't speak this language, but looks like `,` is used as a space, but somehow the tool is splitting it as an array element instead.

 ![image](https://user-images.githubusercontent.com/853051/73894015-0f448400-4830-11ea-8a65-a9146a2ca898.png)

https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/36

**Comment by nvkelso** [comment]
Original raw JSON:

```
"name:jbo_x_variant":[
        "niu,IORK. zei tcadu"
    ],
```

https://data.whosonfirst.org/859/775/39/85977539.geojson

**Comment by iandees** [comment]
There seems to be a bug/feature in the library I'm using for handing lists that assumes it should split by commas when the parsed array of items has a single item. I fixed this by disabling the "delimiters" functionality for these fields.

**Comment by nvkelso** [comment]
Verified in https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/40/files.
