### ISSUE TITLE
Typo in export error message

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#27]
"Problem validating changes: Error in field **mz:is_funky:** field must be an integer"

should be

"Problem validating changes: Error in field **mz:is_funky** field must be an integer"

Minor issue I noticed when testing non-int value changes.

**Comment by nvkelso** [comment]
(the trailing `:` after the field name)

**Comment by iandees** [comment]
The comma is there on purpose to provide separation between the field name and the error message for that field name. How can I make that cleaner?

**Comment by stepps00** [comment]
Ahh, I see.. maybe:

"Problem validating changes: Error in field mz:is_funky (field must be an integer)"?

**Comment by iandees** [comment]
I like it!

**Comment by iandees** [comment]
This should be fixed, but will be a little tricky to test because this is caught by JavaScript before it even gets to the server (where this error message is produced).

**Comment by nvkelso** [comment]
Not sure how to test this one as I don't see any detailed error messages displayed?

![image](https://user-images.githubusercontent.com/853051/74069901-59ef0900-49b4-11ea-8cc1-2a8ea1a61121.png)

**Comment by iandees** [comment]
There are no detailed error messages. The problem fields are highlighted in red.

**Comment by nvkelso** [comment]
Let's just close this then.
