### ISSUE TITLE
BLOCKED: Add favicon

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#28]
Right now it looks like a Github tab, but isn't.

How about a wolf icon? See images in attached ZIP.

```
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
```

[afd5cfdf4fb0f9c8231e5440465e74fe.ico.zip](https://github.com/iandees/wof-editor/files/4162628/afd5cfdf4fb0f9c8231e5440465e74fe.ico.zip)

**Comment by nvkelso** [comment]
<img width="16" alt="favicon-32x32" src="https://user-images.githubusercontent.com/853051/73896252-38b4de00-4837-11ea-882b-a2bac895c2da.png">

**Comment by iandees** [comment]
I added it, but it looks like Lambda isn't serving the image like it's supposed to.

**Comment by nvkelso** [comment]
Once we get this on it's own domain it should just work itself out: https://github.com/iandees/wof-editor/issues/33

**Comment by nvkelso** [comment]
If we go with `writefield` then baseball diamond is better (thanks @iandees). I hacked up this in Photoshop:

<img width="48" alt="favicon-96x96" src="https://user-images.githubusercontent.com/853051/74075788-31253e80-49c9-11ea-9791-9b60c0687487.png">
<img width="16" alt="favicon-32x32" src="https://user-images.githubusercontent.com/853051/74075771-16eb6080-49c9-11ea-940a-b90754f50d16.png">
<img width="8" alt="favicon-16x16" src="https://user-images.githubusercontent.com/853051/74075772-16eb6080-49c9-11ea-9041-ec712059fe7b.png">

Which also kinda looks like a map pin, lol.

**Comment by iandees** [comment]
I updated the favicon and it works with the new domain.

Also, there was some work to get binary responses working properly in 938fec6.

**Comment by nvkelso** [comment]
Working for me!

![image](https://user-images.githubusercontent.com/853051/74187800-230e3280-4c02-11ea-9c48-700dcf584f54.png)
