### ISSUE TITLE
Add note for mz:is_current

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#3]
Something like:

> Defaults to -1 when status is not known, set to 1 when we know a place is active, and 0 if it's closed.

**Comment by stepps00** [comment]
FWIW: https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/is_current.json

**Comment by iandees** [comment]
Added the note:

![image](https://user-images.githubusercontent.com/261584/74060722-332ed380-49b0-11ea-904a-bd57608e52bc.png)

**Comment by nvkelso** [comment]
Verified.
