### ISSUE TITLE
Add View in Spelunker integration

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#30]
Similar to #29, but inside this WOF Editor app add an external link out to "View in Spelunker", which pops people over there so the whole record can be introspected.

**Comment by iandees** [comment]
Added a "view on spelunker" link:

![image](https://user-images.githubusercontent.com/261584/73950697-f8e70880-48c1-11ea-9b59-d687bd40645a.png)

**Comment by nvkelso** [comment]
Working for me!
