### ISSUE TITLE
Unable to "find file" when pushing to Github

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#31]
I made updates to the record for the Province of Las Palmas, Spain but received the following error when trying to push to Github:

```
couldn't find existing file data/856/828/21/85682821.geojson in stepps00/whosonfirst-data-admin-es
```

**Comment by iandees** [comment]
This should be fixed now after b395dcfb050cec0898be0dafec8b8886d4b81d23. Give it another shot?

**Comment by nvkelso** [comment]
@stepps00 over to you.

**Comment by stepps00** [comment]
This is working now :tada:

https://github.com/whosonfirst-data/whosonfirst-data-admin-es/pull/10/files
