### ISSUE TITLE
Existing wof:lang_* properties are not appearing on edit page

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#34]
When editing the record for Las Palmas (85682821), I do not see `wof:lang_x_spoken` or `wof:lang_x_official` properties populated, but the record does have values in those properties.

See: https://github.com/whosonfirst-data/whosonfirst-data-admin-es/pull/10/files, the existing language codes did not appear when I added the `spa` value.

**Comment by iandees** [comment]
This should be fixed, @stepps00.

**Comment by stepps00** [comment]
I see the lang codes now, thanks!
