### ISSUE TITLE
Show default geometry on basemap

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#37]
This is important to verify someone is editing the correct feature.

Can just be an OSM based slippy map in the background.

**Comment by iandees** [comment]
Now there's a map:

![image](https://user-images.githubusercontent.com/261584/74060542-d59a8700-49af-11ea-820d-265c89cefa74.png)

**Comment by thisisaaronland** [comment]
Toner rides again.

**Comment by nvkelso** [comment]
Awesome!
