### ISSUE TITLE
Updating the wof:name of Delhi caused multiple properties to be edited

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#39]
https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/31/files

The only edit I made was to change the `wof:name` to "Delhi1", but as you can see, many properties were updated.

**Comment by nvkelso** [comment]
Oops, that's not good! Let's dig into this before general release of v1.

**Comment by iandees** [comment]
It looks like the `data.whosonfirst.org` version is really old. It's [this one](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-in/3cef27ba4f83d8c13313a2dffe3a0909a5d1343a/data/102/030/425/102030425.geojson), which is [from July](https://github.com/whosonfirst-data/whosonfirst-data-admin-in/blob/3cef27ba4f83d8c13313a2dffe3a0909a5d1343a/data/102/030/425/102030425.geojson).

**Comment by nvkelso** [comment]
Looks like we can crutch off WOF.org for which repo, but we should always read from repo.

And when new feature ask for which repo or full url?

**Comment by stepps00** [comment]
Ahh.. the `data.whosonfirst.org` site can be out of sync, the Github page will have the most up-to-date version of each record.

**Comment by iandees** [comment]
Ok, I am making a request to data.whosonfirst.org to get the `wof:repo` property and then making a request to GitHub to get the actual data from the repo's `master` branch to display for editing.

I also added an endpoint to do this same thing so others can use it if they want: https://93ctehyu4h.execute-api.us-east-1.amazonaws.com/dev/place/85977539/metadata

I made a PR for Delhi after these changes (https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/33) and it looks better.

**Comment by stepps00** [comment]
I made a second PR for Delhi, which looks much cleaner: https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/34/files

Note that the `name:eng_x_colloquial` property currently exists as an empty string (it should be removed), and because it is empty, the wof-editor strips the record of this property. Probably not a blocker because the property doesn't need to be present, but something that caught my eye.

**Comment by nvkelso** [comment]
Agree that empty property should be stripped out.

@iandees what happens when data.whosonfirst.org doesn't have that file? Does it error hard or prompt for a URL &/or repo?

**Comment by iandees** [comment]
For an example: https://93ctehyu4h.execute-api.us-east-1.amazonaws.com/dev/place/512891029831/edit

Gives:

![image](https://user-images.githubusercontent.com/261584/74054506-ce6d7c00-49a3-11ea-9f2b-70e82d211f41.png)

**Comment by iandees** [comment]
Hit send too soon, but the idea is that on that initial page would be a box to enter the URL or the GitHub repo + ID.
