### ISSUE TITLE
Unable to edit wof:name

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#41]
I'm trying to update the `wof:name` value of Zerakpur, India (134/373/049/7/1343730497.geojson), but hitting the following issue:

<img width="1176" alt="Screen Shot 2020-02-18 at 12 58 19 PM" src="https://user-images.githubusercontent.com/18567700/74777488-6eea5880-524e-11ea-845f-856a3b883690.png">

Steps are fairly simple.. 
1. Update the `wof:name` value from "Zerakpur" to "Zirakpur"
2. Click out of the edit box so the green check box appears
3. Hit the "Propose change on Github" button

I also tried updating additional properties along with the `wof:name`, the same error appeared.

**Comment by iandees** [comment]
This should be fixed now. I was looking in the wrong spot on the JSON document for `wof:name` when checking if it was set.

**Comment by stepps00** [comment]
Nice, this is fixed!
