### ISSUE TITLE
Adding new name: values actually sets label: values

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#42]
https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/35
https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/36

In both these cases, I actually added new `name:eng_x_variant` and `name:eng_x_preferred` values, but the `label:` prefix was used to set the new properties instead.

**Comment by iandees** [comment]
Can you be a little more specific about the steps you did here? It looks like you tried adding a language by adding text to the "Filter" box and then specified a preferred and variant value?

**Comment by iandees** [comment]
Ah, found the problem and it's fixed now. :+1:

**Comment by stepps00** [comment]
Nice, thanks! Just in case, steps that caused this:

- Add value the Localized Names "variant" text field with "Eng" selected as the language ("name:eng_x_variant")
- Add value the Localized Names "preferred" text field with "Eng" selected as the language ("name:eng_x_preferred")
- Propose changes to GitHub
- In the PR, notice the prefix for the new properties is `label`, not `name`.

**Comment by stepps00** [comment]
Confirmed fix: https://github.com/whosonfirst-data/whosonfirst-data-admin-in/pull/37/files
