### ISSUE TITLE
PR comment should say "WriteField" not WOF Editor

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#45]
I just updated a locality record in India and noticed the PR comment still references "WOF Editor", rather than WriteField / Write Field.

> Updating data/129/364/746/5/1293647465.geojson using the WOF Editor

The "WOF Editor" texts links to this wof-editor repo, so maybe this is intentional.

**Comment by nvkelso** [comment]
Dup of https://github.com/iandees/wof-editor/issues/43.
