### ISSUE TITLE
Editing a name causes a concordance value to change

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#49]
https://github.com/whosonfirst-data/whosonfirst-data-admin-at/pull/11/files

Browsing records in the Spelunker, I noticed some bunk characters in a name translation in the Vorarlberg region record. I was able to make the name change, but the Digital Envoy concordance value was changed from an integer to a string.

Looks like this was discussed [here](https://github.com/iandees/wof-editor/issues/13#issuecomment-583642199), but I'm opening this because it seems odd for a value to change when it is not being edited.

**Comment by iandees** [comment]
Ideas for solution:
* Pass along data type in form?
* Don't consider the change if the string representation of the original is the same as what's in the form?
