### ISSUE TITLE
Add note for EDTF form elements

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#5]
Similar to https://github.com/iandees/wof-editor/issues/3.

We don't need a date picker (as EDTF date notation is more flexible), but for (edtf:cessation, edtf:deprecated, edtf:inception, edtf:superseded)

Let's add example text to the first one, like:

> Supports EDTF date notation like: 2000, 2000-01, 2000-01-01 and approximate dates like ~2000. Defaults to uuuu when unknown.

**Comment by stepps00** [comment]
Should this issue track formatting the EDTF date, too? Or is that a separate issue?

FWIW: https://github.com/richardtallent/EdtfDotNet/blob/master/Edtf/EdtfRegexPattern.txt

**Comment by iandees** [comment]
I appended this note to the existing text:

![image](https://user-images.githubusercontent.com/261584/74060672-18f4f580-49b0-11ea-9516-9c0e865f5427.png)

**Comment by nvkelso** [comment]
Verified.
