### ISSUE TITLE
Error when loading WOF records

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#60]
Hey :wave:

When trying to load WOF records for editing in the Write Field tool, I now see this error:

<img width="1152" alt="Screen Shot 2022-01-31 at 4 37 42 PM" src="https://user-images.githubusercontent.com/18567700/151895906-40dd22b2-e5f3-4b79-b4c1-a9de6aa60645.png">

This seems to happen with any WOF record. I've logged out/back in, and the issue persists.

**Comment by iandees** [comment]
There appears to be some sort of blocking on data.whosonfirst.org preventing the app from getting the data. I'm asking Aaron if he knows what's up.

**Comment by iandees** [comment]
In the meantime, if you can find the doc you want to edit in Github, you can append it to the edit page like so:

```
https://writefield.nextzen.org/place/edit?url=https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-me/master/data/127/634/547/1/1276345471.geojson
```

**Comment by iandees** [comment]
It's important the URL parameter is the "raw" URL for the document.

**Comment by stepps00** [comment]
Ah great, the `url` option is really helpful. I was able to create a PR by pulling in the raw geojson from Github in [a new PR](https://github.com/whosonfirst-data/whosonfirst-data-admin-fr/pull/62).

**Comment by nvkelso** [comment]
As a quick workaround, we could modify the Spelunker sidebar box to include a link to Edit in Write Field with the fully constructed URL?

Eg at the bottom of the `Other` section: 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/853051/217920444-6338d595-bbda-4bb6-8884-df3746e130eb.png">
