### ISSUE TITLE
Unable to add a concordance to a place without existing concordances

### ISSUE THREAD

**Issue by stepps00** [iandees/wof-editor#73]
I tried adding a new Wikidata concordance to a Who's On First record today using the Write Field tool, but was unable to.

Adding concordances to place records that already have a concordance does seem to work as expected.. this seems to only affect records without any existing concordances.

**Comment by iandees** [comment]
Can you share a WOF ID where you ran into this issue?

**Comment by stepps00** [comment]
Sure, this was the record I was having trouble with:

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-de/master/data/110/894/723/3/1108947233.geojson

I was hoping to add the `wd:id` concordance of "Q1561876".

**Comment by iandees** [comment]
Looks like I don't have the deploy info on this laptop, so this isn't deployed quite yet.
