### ISSUE TITLE
Indicate total number of translated names and labels

### ISSUE THREAD

**Issue by nvkelso** [iandees/wof-editor#9]
Add text to say: “There are X localized names, English is shown. Add more to the filter to see more…”

- names
- labels

Right now it only looks like English is there, but sometimes we have dozens and hundreds of name translations!

**Comment by iandees** [comment]
Added text like this:

![image](https://user-images.githubusercontent.com/261584/74089530-8dd73680-4a67-11ea-953d-11995f2c75c9.png)

**Comment by nvkelso** [comment]
Huzzah!
